//! Dispatch from `JobType` to the concrete handler. Every function here matches
//! exhaustively on `JobType`, so adding a variant fails to compile until all
//! four components of the new job type exist.

use super::dispatch::{JobKind, JobTemplate};
use super::handler::*;
use super::{game, game_pair, leave_gen, opening_rack};
use crate::auth::WorkerIdentity;
use crate::error::{AppError, AppResult};
use crate::models::job::*;
use sqlx::PgConnection;
use uuid::Uuid;

/// The outcome of trying to get one unit of work out of a job.
// One value per claim attempt, moved straight to the caller and never stored,
// so the size of the `Task` variant costs nothing worth a box.
#[allow(clippy::large_enum_variant)]
pub enum Acquired {
    /// `created` distinguishes a task generated by this claim from one being
    /// re-dispatched, which is what `jobs.tasks_total` counts. It rides here
    /// rather than being written on the spot so the claim's single
    /// `UPDATE jobs` can carry it, keeping the job's row lock as late in the
    /// transaction as it already was.
    Task { task_id: Uuid, request: TaskRequest, created: bool },
    /// This job has nothing to hand out right now; try the next one.
    NoWork,
    /// Leave generation only: the current generation is finished and must be
    /// aggregated before more tasks exist. Handled outside the transaction.
    NeedsGenerationTransition { generation: i32 },
    /// Leave generation only: the current generation's rack universe has not
    /// been written yet. It is seeded on its own task, and the job has nothing
    /// to hand out until that commits.
    NeedsUniverse { generation: i32 },
    /// Leave generation only: nothing is left to hand out or in flight, but
    /// accepted results are still staged, so whether the generation is complete
    /// is not yet known. The caller merges them, off the request; this job has
    /// nothing to hand out until the next claim looks again.
    NeedsLeaveMerge { generation: i32 },
    /// Leave generation only: all configured generations are done.
    JobFinished,
}

/// One claim decision for `job`, under its dispatch lock.
///
/// `template` is the job's immutable configuration (`dispatch::JobTemplate`),
/// read once per process rather than once per claim: with it in hand the only
/// reads made under the lock are the ones that change from claim to claim --
/// the seed cursor, the available tasks, a stored request.
pub async fn acquire(
    conn: &mut PgConnection,
    job: &Job,
    identity: &WorkerIdentity,
    template: &JobTemplate,
) -> AppResult<Acquired> {
    // Every claim decision for a job is made under its dispatch lock, the
    // re-dispatch of an existing task included. That path used to skip it, and
    // it is the one a purge could not stop: a claim holding a task row it had
    // just selected would wait on the job's row lock the purge held, while the
    // purge waited on that same task row to delete it -- a deadlock, which
    // Postgres breaks by failing one of the two. Claims against one job
    // already serialized on that row lock (`issue_claim` bumps
    // `claims_issued`), so taking the advisory lock first costs a little more
    // of the same wait and nothing new.
    if !super::try_lock_job_dispatch(&mut *conn, job.id).await? {
        return Ok(Acquired::NoWork);
    }

    // A task whose claim timed out drops back to `available`, and so does a
    // task with redundancy left to fill, so re-dispatching those comes first.
    // For games this is what keeps the seed space covered: an abandoned batch
    // is replayed rather than skipped, since nothing else would ever revisit
    // those seeds.
    //
    // Leave generation does this itself, under its claim lock and only for the
    // current generation (see `generate_leave_gen`).
    if !matches!(job.job_type, JobType::LeaveGeneration) {
        if let Some(task_id) = next_available(conn, job.id, identity, None).await? {
            let request = load_request(conn, template, task_id).await?;
            return Ok(Acquired::Task { task_id, request, created: false });
        }
    }

    // Every job type generates its tasks at claim time; there is no
    // pre-populated strategy any more.
    match job.job_type {
        JobType::OpeningRack => generate_opening_rack(conn, job, template).await,
        JobType::Games => generate_games(conn, job, template).await,
        JobType::GamePairs => generate_game_pairs(conn, job, template).await,
        JobType::LeaveGeneration => generate_leave_gen(conn, job, identity, template).await,
    }
}

async fn generate_opening_rack(
    conn: &mut PgConnection,
    job: &Job,
    template: &JobTemplate,
) -> AppResult<Acquired> {
    // `acquire` already holds the job's dispatch lock, which is what this
    // needs: `next_request` addresses the next slice with `MAX(seed)`, which a
    // concurrent claim's uncommitted task is invisible to.
    let JobKind::OpeningRack { config, player, index } = &template.kind else {
        return Err(template.mismatch("opening_rack"));
    };
    let Some((start, request)) =
        opening_rack::next_request(conn, job.id, config, &template.data, index, player).await?
    else {
        // The rack space is exhausted; nothing left to hand out.
        return Ok(Acquired::NoWork);
    };

    let task_id = insert_on_demand_task(conn, job.id, start).await?;
    opening_rack::insert_range(conn, task_id, config, &template.data, start, request.racks.len())
        .await?;
    Ok(Acquired::Task { task_id, request: TaskRequest::OpeningRack(request), created: true })
}

/// An available task this worker may take, locked with `FOR UPDATE SKIP LOCKED`
/// so concurrent claimers never serialize on one row.
///
/// Excludes tasks this identity already holds a slot on, live or completed.
/// With redundancy above 1 a task stays `available` after its first claim, and
/// the per-identity unique index refuses a second slot for the same worker --
/// correctly, since redundancy means *independent* workers. Without this
/// filter the oldest such task would be selected again on every attempt, the
/// insert would fail every time, and the worker would get nothing at all until
/// someone else filled the slot.
///
/// `leave_generation`, when set, restricts it to a leave job's tasks for that
/// generation.
async fn next_available(
    conn: &mut PgConnection,
    job_id: Uuid,
    identity: &WorkerIdentity,
    leave_generation: Option<i32>,
) -> AppResult<Option<Uuid>> {
    Ok(sqlx::query_scalar::<_, Uuid>(
        "SELECT t.id FROM tasks t
         WHERE t.job_id = $1 AND t.state = 'available'
           AND NOT EXISTS (
               SELECT 1 FROM task_claims c
               WHERE c.task_id = t.id
                 AND c.state NOT IN ('abandoned', 'declined')
                 AND (c.claimed_by_user_id = $2 OR c.claimed_by_anon_uuid = $3)
           )
           AND ($4::int IS NULL OR EXISTS (
               SELECT 1 FROM leave_requests r
               WHERE r.task_id = t.id AND r.generation = $4
           ))
         ORDER BY t.created_at
         FOR UPDATE OF t SKIP LOCKED
         LIMIT 1",
    )
    .bind(job_id)
    .bind(identity.user_id())
    .bind(identity.anon_uuid())
    .bind(leave_generation)
    .fetch_optional(conn)
    .await?)
}

/// Reads a stored request back, for a task being re-dispatched.
pub async fn load_request(
    conn: &mut PgConnection,
    template: &JobTemplate,
    task_id: Uuid,
) -> AppResult<TaskRequest> {
    Ok(match template.kind {
        JobKind::OpeningRack { .. } => TaskRequest::OpeningRack(
            opening_rack::OpeningRackHandler::load_request(conn, template, task_id).await?,
        ),
        JobKind::Games { .. } => {
            TaskRequest::Games(game::GameHandler::load_request(conn, template, task_id).await?)
        }
        JobKind::GamePairs { .. } => TaskRequest::GamePairs(
            game_pair::GamePairHandler::load_request(conn, template, task_id).await?,
        ),
        JobKind::LeaveGeneration { .. } => TaskRequest::LeaveGeneration(
            leave_gen::LeaveGenHandler::load_request(conn, template, task_id).await?,
        ),
    })
}

async fn generate_games(
    conn: &mut PgConnection,
    job: &Job,
    template: &JobTemplate,
) -> AppResult<Acquired> {
    // See `generate_opening_rack`: the seed cursor is `MAX(seed)`, read under
    // the dispatch lock `acquire` holds.
    let JobKind::Games { config, player1, player2 } = &template.kind else {
        return Err(template.mismatch("games"));
    };
    let Some((seed, request)) =
        game::next_request(conn, job.id, config, &template.data, player1, player2).await?
    else {
        // Every game up to `max_games` has been handed out.
        return Ok(Acquired::NoWork);
    };
    let task_id = insert_on_demand_task(conn, job.id, seed).await?;
    super::insert_game_request(
        conn,
        task_id,
        &request,
        config.player1_config_id,
        config.player2_config_id,
    )
    .await?;
    Ok(Acquired::Task { task_id, request: TaskRequest::Games(request), created: true })
}

async fn generate_game_pairs(
    conn: &mut PgConnection,
    job: &Job,
    template: &JobTemplate,
) -> AppResult<Acquired> {
    // See `generate_opening_rack`: the seed cursor is `MAX(seed)`, read under
    // the dispatch lock `acquire` holds.
    let JobKind::GamePairs { config, player1, player2 } = &template.kind else {
        return Err(template.mismatch("game_pairs"));
    };
    let Some((seed, request)) =
        game_pair::next_request(conn, job.id, config, &template.data, player1, player2).await?
    else {
        // Every pair up to `max_pairs` has been handed out.
        return Ok(Acquired::NoWork);
    };
    let task_id = insert_on_demand_task(conn, job.id, seed).await?;
    super::insert_game_request(
        conn,
        task_id,
        &request,
        config.player1_config_id,
        config.player2_config_id,
    )
    .await?;
    Ok(Acquired::Task { task_id, request: TaskRequest::GamePairs(request), created: true })
}

async fn generate_leave_gen(
    conn: &mut PgConnection,
    job: &Job,
    identity: &WorkerIdentity,
    template: &JobTemplate,
) -> AppResult<Acquired> {
    let JobKind::LeaveGeneration { config, lexicon } = &template.kind else {
        return Err(template.mismatch("leave_generation"));
    };

    // `acquire` holds the job's dispatch lock for the rest of this transaction,
    // taken before anything here is read: what to hand out, and whether the
    // generation can be closed, are decisions that must not be made from a
    // view of the job that another claim is in the middle of changing. See
    // PLAN.md's leave-generation claim steps.

    // A reopened task -- its claim timed out -- is reissued before a new one is
    // generated, as for every job type, but only here: after the lock, so the
    // reissued claim is visible to the in-flight check of every claim that
    // follows it, and only for the current generation. A task from a
    // generation that has since closed is left alone; its racks would be
    // played with a KLV that is no longer current, and its result discarded.
    let Some(generation) = leave_gen::current_generation(&mut *conn, job.id, config).await? else {
        return Ok(Acquired::JobFinished);
    };

    // While this generation's transition is running there is nothing to hand
    // out for it, and that has to be checked before the reissue below rather
    // than only in `next_step`. The generation does not read as closed until
    // the transition commits its artifact row, so without this a task left
    // `available` by a lapsed claim would be reissued mid-transition: the
    // worker would play it and fold its occurrences into the very rows the
    // transition is streaming, so the KLV it uploaded would no longer be
    // reproducible from the database -- and a hash mismatch is the one signal
    // `rebuild_artifacts` reserves for a corrupted object.
    if leave_gen::transition_in_progress(&mut *conn, job.id, generation).await? {
        return Ok(Acquired::NoWork);
    }

    // Generations past the first get their rack universe when a claim first
    // asks for work in one, rather than from the transition that closed the
    // generation before -- but not inside the claim: it is millions of rows,
    // and a request the client gives up on rolls it back. The caller seeds it
    // on its own task. Checked before anything reads `leave_rack_progress`,
    // which is what selection and the in-flight check are about to do.
    if !leave_gen::universe_exists(&mut *conn, job.id, generation).await? {
        return Ok(Acquired::NeedsUniverse { generation });
    }

    if let Some(task_id) = next_available(&mut *conn, job.id, identity, Some(generation)).await? {
        let request = load_request(conn, template, task_id).await?;
        return Ok(Acquired::Task { task_id, request, created: false });
    }

    match leave_gen::next_step(conn, job.id, config, &template.data, lexicon).await? {
        leave_gen::LeaveGenStep::Dispatch(request) => {
            // The seed drawn for the task is its seed on the `tasks` row too:
            // every task has one, and the unique index on (job_id, seed) turns
            // the negligible chance of two draws colliding into a retried
            // claim rather than two tasks replaying each other's games.
            let task_id = insert_on_demand_task(conn, job.id, request.seed as i64).await?;
            leave_gen::insert_request(conn, task_id, &request).await?;
            Ok(Acquired::Task { task_id, request: TaskRequest::LeaveGeneration(request), created: true })
        }
        leave_gen::LeaveGenStep::Transition { generation } => {
            Ok(Acquired::NeedsGenerationTransition { generation })
        }
        leave_gen::LeaveGenStep::NeedsMerge { generation } => {
            Ok(Acquired::NeedsLeaveMerge { generation })
        }
        leave_gen::LeaveGenStep::Finished => Ok(Acquired::JobFinished),
        // Another worker's request is aggregating the generation. This one has
        // nothing to do until that finishes, and the next job in the
        // scheduler's order may well have work.
        leave_gen::LeaveGenStep::TransitionInProgress { .. } => Ok(Acquired::NoWork),
        leave_gen::LeaveGenStep::NoWorkYet => Ok(Acquired::NoWork),
    }
}

/// On-demand tasks are inserted `available` and immediately claimed by the
/// caller in the same transaction, so the counter bookkeeping is identical on
/// every path. Every task carries the seed its games are played from.
async fn insert_on_demand_task(
    conn: &mut PgConnection,
    job_id: Uuid,
    seed: i64,
) -> AppResult<Uuid> {
    Ok(sqlx::query_scalar::<_, Uuid>(
        "INSERT INTO tasks (job_id, seed, state) VALUES ($1, $2, 'available') RETURNING id",
    )
    .bind(job_id)
    .bind(seed)
    .fetch_one(conn)
    .await?)
}

/// Validate, normalize and store a worker submission.
///
/// `first_result` says whether this is the first accepted result for its task,
/// which the caller reads from the task's `accepted_count` under the task's row
/// lock. Only a first result adds to the job's running totals or folds into a
/// leave generation: redundant claims replay the same deterministic work.
///
/// `template` is the job's immutable configuration, which is where the batch
/// size a task was dispatched with and the number of moves to keep per
/// position come from: both are job settings the request rows denormalize, so
/// reading them from the template costs no round trip inside the task's lock.
pub async fn store_result(
    conn: &mut PgConnection,
    template: &JobTemplate,
    task_id: Uuid,
    claim_id: Uuid,
    first_result: bool,
    payload: Box<serde_json::value::RawValue>,
) -> AppResult<ProgressDelta> {
    /// Straight from the submission's text into its typed response. It went
    /// through a `serde_json::Value` first, which holds every object as a
    /// B-tree node and every key as its own allocation -- ten to twenty times
    /// the JSON's size, and a result may be 64 MiB. A few of those at once
    /// were enough to have the one web task killed for memory.
    fn decode<T: serde::de::DeserializeOwned>(payload: &serde_json::value::RawValue) -> AppResult<T> {
        serde_json::from_str(payload.get())
            .map_err(|e| AppError::bad_request(format!("malformed task response: {e}")))
    }

    /// Decode and validate a submission on the blocking pool.
    ///
    /// A result is up to 64 MiB of JSON: ten thousand racks with their ranked
    /// moves and plies, or every rack a ten-thousand-game leave task drew.
    /// Turning that into typed records and running the plausibility rules over
    /// it is tens to hundreds of milliseconds of computation with no `await`
    /// in it, and an async worker thread that does not yield can hold up every
    /// other request the server has (see `exports::upload_rows`). The hop costs
    /// microseconds, against a transaction of a dozen round trips.
    async fn normalize<H>(payload: Box<serde_json::value::RawValue>) -> AppResult<H::Record>
    where
        H: JobHandler,
        H::Response: Send + 'static,
        H::Record: Send + 'static,
    {
        tokio::task::spawn_blocking(move || H::process_response(decode::<H::Response>(&payload)?))
            .await
            .map_err(|e| AppError::internal(format!("validating a task response failed: {e}")))?
    }

    match &template.kind {
        JobKind::OpeningRack { .. } => {
            let record = normalize::<opening_rack::OpeningRackHandler>(payload).await?;
            let racks: Vec<String> =
                record.positions.iter().map(|p| p.rack.clone()).collect();
            opening_rack::check_batch_against_task(conn, template, task_id, &racks).await?;
            opening_rack::OpeningRackHandler::insert_record(conn, template, task_id, claim_id, &record)
                .await?;
            // One row per rack, and the unique index on (task_claim_id, rack)
            // means the insert above would have failed on a duplicate, so the
            // submission's length is its distinct-rack count. Racks never
            // repeat across tasks either: each task analyses its own slice of
            // the enumerated space.
            Ok(ProgressDelta::first_result(first_result, 0, record.positions.len() as i64))
        }
        JobKind::Games { config, .. } => {
            let record = normalize::<game::GameHandler>(payload).await?;
            // The batch size was fixed when the task was handed out -- it is
            // the job's, denormalized onto every request -- so a result of any
            // other size is answering a question nobody asked.
            super::plausibility::check_batch_size(
                record.all_games.games,
                super::plausibility::games_dispatched(config.games_per_batch, false),
            )?;
            game::GameHandler::insert_record(conn, template, task_id, claim_id, &record).await?;
            Ok(ProgressDelta::first_result(first_result, record.all_games.games as i64, 0))
        }
        JobKind::GamePairs { config, .. } => {
            let record = normalize::<game_pair::GamePairHandler>(payload).await?;
            // A pairs request counts pairs; each is two games.
            super::plausibility::check_batch_size(
                record.all_games.games,
                super::plausibility::games_dispatched(config.pairs_per_batch, true),
            )?;
            game_pair::GamePairHandler::insert_record(conn, template, task_id, claim_id, &record)
                .await?;
            // Games, not pairs, for both job types: the pairs count is half of
            // it and is derived where it is displayed.
            Ok(ProgressDelta::first_result(first_result, record.all_games.games as i64, 0))
        }
        JobKind::LeaveGeneration { config, .. } => {
            let record = normalize::<leave_gen::LeaveGenHandler>(payload).await?;
            // Against the games the task was dispatched with, which is the
            // job's `num_iterations` on every request: occurrences are summed
            // on receipt, and an impossible count does not only mislead, it
            // overflows the merge that sums it.
            super::plausibility::check_rack_occurrence_total(&record.racks, config.num_iterations)?;
            if first_result {
                leave_gen::LeaveGenHandler::insert_record(conn, template, task_id, claim_id, &record)
                    .await?;
            } else {
                leave_gen::credit_claim(conn, task_id, claim_id, &record).await?;
            }
            Ok(ProgressDelta::default())
        }
    }
}

/// A turn to store a large result, taken by the submit path *before* it opens
/// its transaction and held until it commits; `None` for an ordinary result,
/// which never waits.
///
/// At the 64 MiB ceiling one submission holds the body, its text, the typed
/// response and the record -- a quarter of a gigabyte -- and nothing bounded
/// how many ran at once on the one 2 GB task. The wait is outside the
/// transaction because inside it, as it first was, each waiter held a pool
/// connection and its claim and task rows for up to thirty seconds, and the
/// permit ended before the insert that still held the record.
pub async fn large_result_turn(
    bytes: usize,
) -> AppResult<Option<tokio::sync::SemaphorePermit<'static>>> {
    if bytes < LARGE_RESULT_BYTES {
        return Ok(None);
    }
    let permit = tokio::time::timeout(LARGE_RESULT_WAIT, LARGE_RESULT_DECODES.acquire())
        .await
        .map_err(|_| AppError {
            retry_after: Some(30),
            ..AppError::new(
                axum::http::StatusCode::SERVICE_UNAVAILABLE,
                "unavailable",
                "the server is storing other large results; try again shortly",
            )
        })?
        .map_err(|e| AppError::internal(format!("large-result semaphore closed: {e}")))?;
    Ok(Some(permit))
}

/// A result at least this large takes a [`large_result_turn`].
const LARGE_RESULT_BYTES: usize = 8 * 1024 * 1024;
/// How many large results are decoded at once.
static LARGE_RESULT_DECODES: tokio::sync::Semaphore = tokio::sync::Semaphore::const_new(3);
/// How long a large result waits for a turn before its worker is told to come
/// back (`503`, which MAGPIE retries).
const LARGE_RESULT_WAIT: std::time::Duration = std::time::Duration::from_secs(30);

/// What one accepted result adds to its job's running progress totals: games
/// played, opening racks analysed. Returned rather than written, so the submit
/// path can make every change to the job's row in one statement, last.
///
/// Only the first accepted result for its task counts. The reads these totals
/// replace both selected one result per task -- the aggregates they summed
/// describe the same deterministic work on every redundant claim, so counting
/// all of them would multiply the total by the job's redundancy (PLAN.md,
/// "What these reads cost"). "First" comes from the task's `accepted_count`,
/// read by `submit_result` under the task's row lock before anything is
/// stored: every accepted result increments it in the transaction that stores
/// the result, and that transaction holds the same lock, so two submissions
/// arriving together cannot both read zero.
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq)]
pub struct ProgressDelta {
    pub games_completed: i64,
    pub racks_analyzed: i64,
}

impl ProgressDelta {
    fn first_result(first_result: bool, games: i64, racks: i64) -> Self {
        if first_result {
            ProgressDelta { games_completed: games, racks_analyzed: racks }
        } else {
            ProgressDelta::default()
        }
    }
}

/// The part of job initialization that cannot run inside the creating
/// transaction: generation 1's zeroed KLV is a multi-megabyte build and an
/// object-store write. Called after the transaction commits, and again at
/// activation if it has not happened yet. Idempotent.
pub async fn initialize_job_artifacts(
    state: &crate::state::AppState,
    job: &Job,
) -> AppResult<()> {
    if job.job_type != JobType::LeaveGeneration {
        return Ok(());
    }
    let mut conn = state.pool.acquire().await?;
    let job_data = super::load_job_data(&mut conn, job.id).await?;
    drop(conn);
    leave_gen::seed_zero_generation(
        &state.pool,
        &state.artifacts,
        &state.magpie,
        &state.builders,
        job.id,
        &job_data.letterdist,
    )
    .await?;
    Ok(())
}

/// Whether a job has everything `initialize_job_artifacts` writes. Only leave
/// generation writes anything.
pub async fn job_artifacts_ready(pool: &sqlx::PgPool, job: &Job) -> AppResult<bool> {
    if job.job_type != JobType::LeaveGeneration {
        return Ok(true);
    }
    Ok(sqlx::query_scalar::<_, bool>(
        "SELECT EXISTS (SELECT 1 FROM leave_generation_artifacts
                        WHERE job_id = $1 AND generation = 0)",
    )
    .bind(job.id)
    .fetch_one(pool)
    .await?)
}
