//! Dispatch from `JobType` to the concrete handler. Every function here matches
//! exhaustively on `JobType`, so adding a variant fails to compile until all
//! four components of the new job type exist.

use super::handler::*;
use super::{game, game_pair, leave_gen, load_job_data, opening_rack};
use crate::artifacts::ArtifactStore;
use crate::auth::WorkerIdentity;
use crate::error::{AppError, AppResult};
use crate::models::job::*;
use sqlx::PgConnection;
use uuid::Uuid;

/// The outcome of trying to get one unit of work out of a job.
// One value per claim attempt, moved straight to the caller and never stored,
// so the size of the `Task` variant costs nothing worth a box.
#[allow(clippy::large_enum_variant)]
pub enum Acquired {
    /// `created` distinguishes a task generated by this claim from one being
    /// re-dispatched, which is what `jobs.tasks_total` counts. It rides here
    /// rather than being written on the spot so the claim's single
    /// `UPDATE jobs` can carry it, keeping the job's row lock as late in the
    /// transaction as it already was.
    Task { task_id: Uuid, request: TaskRequest, created: bool },
    /// This job has nothing to hand out right now; try the next one.
    NoWork,
    /// Leave generation only: the current generation is finished and must be
    /// aggregated before more tasks exist. Handled outside the transaction.
    NeedsGenerationTransition { generation: i32 },
    /// Leave generation only: the current generation's rack universe has not
    /// been written yet. It is seeded on its own task, and the job has nothing
    /// to hand out until that commits.
    NeedsUniverse { generation: i32 },
    /// Leave generation only: all configured generations are done.
    JobFinished,
}

pub async fn acquire(
    conn: &mut PgConnection,
    job: &Job,
    identity: &WorkerIdentity,
) -> AppResult<Acquired> {
    // Every claim decision for a job is made under its dispatch lock, the
    // re-dispatch of an existing task included. That path used to skip it, and
    // it is the one a purge could not stop: a claim holding a task row it had
    // just selected would wait on the job's row lock the purge held, while the
    // purge waited on that same task row to delete it -- a deadlock, which
    // Postgres breaks by failing one of the two. Claims against one job
    // already serialized on that row lock (`issue_claim` bumps
    // `claims_issued`), so taking the advisory lock first costs a little more
    // of the same wait and nothing new.
    if !super::try_lock_job_dispatch(&mut *conn, job.id).await? {
        return Ok(Acquired::NoWork);
    }

    // A task whose claim timed out drops back to `available`, and so does a
    // task with redundancy left to fill, so re-dispatching those comes first.
    // For games this is what keeps the seed space covered: an abandoned batch
    // is replayed rather than skipped, since nothing else would ever revisit
    // those seeds.
    //
    // Leave generation does this itself, under its claim lock and only for the
    // current generation (see `generate_leave_gen`).
    if !matches!(job.job_type, JobType::LeaveGeneration) {
        if let Some(task_id) = next_available(conn, job.id, identity, None).await? {
            let request = load_request(conn, job.job_type, task_id).await?;
            return Ok(Acquired::Task { task_id, request, created: false });
        }
    }

    // Every job type generates its tasks at claim time; there is no
    // pre-populated strategy any more.
    match job.job_type {
        JobType::OpeningRack => generate_opening_rack(conn, job).await,
        JobType::Games => generate_games(conn, job).await,
        JobType::GamePairs => generate_game_pairs(conn, job).await,
        JobType::LeaveGeneration => generate_leave_gen(conn, job, identity).await,
    }
}

async fn generate_opening_rack(conn: &mut PgConnection, job: &Job) -> AppResult<Acquired> {
    // `acquire` already holds the job's dispatch lock, which is what this
    // needs: `next_request` addresses the next slice with `MAX(seed)`, which a
    // concurrent claim's uncommitted task is invisible to.
    let config = sqlx::query_as::<_, OpeningRackConfig>(
        "SELECT * FROM job_opening_rack_config WHERE job_id = $1",
    )
    .bind(job.id)
    .fetch_one(&mut *conn)
    .await?;

    let job_data = load_job_data(&mut *conn, job.id).await?;
    let Some((start, request)) =
        opening_rack::next_request(conn, job.id, &config, &job_data).await?
    else {
        // The rack space is exhausted; nothing left to hand out.
        return Ok(Acquired::NoWork);
    };

    let task_id = insert_on_demand_task(conn, job.id, Some(start)).await?;
    opening_rack::insert_range(conn, task_id, &config, &job_data, start, request.racks.len())
        .await?;
    Ok(Acquired::Task { task_id, request: TaskRequest::OpeningRack(request), created: true })
}

/// An available task this worker may take, locked with `FOR UPDATE SKIP LOCKED`
/// so concurrent claimers never serialize on one row.
///
/// Excludes tasks this identity already holds a slot on, live or completed.
/// With redundancy above 1 a task stays `available` after its first claim, and
/// the per-identity unique index refuses a second slot for the same worker --
/// correctly, since redundancy means *independent* workers. Without this
/// filter the oldest such task would be selected again on every attempt, the
/// insert would fail every time, and the worker would get nothing at all until
/// someone else filled the slot.
///
/// `leave_generation`, when set, restricts it to a leave job's tasks for that
/// generation.
async fn next_available(
    conn: &mut PgConnection,
    job_id: Uuid,
    identity: &WorkerIdentity,
    leave_generation: Option<i32>,
) -> AppResult<Option<Uuid>> {
    Ok(sqlx::query_scalar::<_, Uuid>(
        "SELECT t.id FROM tasks t
         WHERE t.job_id = $1 AND t.state = 'available'
           AND NOT EXISTS (
               SELECT 1 FROM task_claims c
               WHERE c.task_id = t.id
                 AND c.state NOT IN ('abandoned', 'declined')
                 AND (c.claimed_by_user_id = $2 OR c.claimed_by_anon_uuid = $3)
           )
           AND ($4::int IS NULL OR EXISTS (
               SELECT 1 FROM leave_requests r
               WHERE r.task_id = t.id AND r.generation = $4
           ))
         ORDER BY t.created_at
         FOR UPDATE OF t SKIP LOCKED
         LIMIT 1",
    )
    .bind(job_id)
    .bind(identity.user_id())
    .bind(identity.anon_uuid())
    .bind(leave_generation)
    .fetch_optional(conn)
    .await?)
}

pub async fn load_request(
    conn: &mut PgConnection,
    job_type: JobType,
    task_id: Uuid,
) -> AppResult<TaskRequest> {
    Ok(match job_type {
        JobType::OpeningRack => TaskRequest::OpeningRack(
            opening_rack::OpeningRackHandler::load_request(conn, task_id).await?,
        ),
        JobType::Games => {
            TaskRequest::Games(game::GameHandler::load_request(conn, task_id).await?)
        }
        JobType::GamePairs => {
            TaskRequest::GamePairs(game_pair::GamePairHandler::load_request(conn, task_id).await?)
        }
        JobType::LeaveGeneration => TaskRequest::LeaveGeneration(
            leave_gen::LeaveGenHandler::load_request(conn, task_id).await?,
        ),
    })
}

async fn generate_games(conn: &mut PgConnection, job: &Job) -> AppResult<Acquired> {
    // See `generate_opening_rack`: the seed cursor is `MAX(seed)`, read under
    // the dispatch lock `acquire` holds.
    let config = sqlx::query_as::<_, GameConfig>("SELECT * FROM job_game_config WHERE job_id = $1")
        .bind(job.id)
        .fetch_one(&mut *conn)
        .await?;

    let job_data = load_job_data(&mut *conn, job.id).await?;
    let Some((seed, request)) = game::next_request(conn, job.id, &config, &job_data).await? else {
        // Every game up to `max_games` has been handed out.
        return Ok(Acquired::NoWork);
    };
    let task_id = insert_on_demand_task(conn, job.id, Some(seed)).await?;
    super::insert_game_request(
        conn,
        task_id,
        &request,
        config.player1_config_id,
        config.player2_config_id,
    )
    .await?;
    Ok(Acquired::Task { task_id, request: TaskRequest::Games(request), created: true })
}

async fn generate_game_pairs(conn: &mut PgConnection, job: &Job) -> AppResult<Acquired> {
    // See `generate_opening_rack`: the seed cursor is `MAX(seed)`, read under
    // the dispatch lock `acquire` holds.
    let config =
        sqlx::query_as::<_, GamePairConfig>("SELECT * FROM job_game_pair_config WHERE job_id = $1")
            .bind(job.id)
            .fetch_one(&mut *conn)
            .await?;

    let job_data = load_job_data(&mut *conn, job.id).await?;
    let Some((seed, request)) =
        game_pair::next_request(conn, job.id, &config, &job_data).await?
    else {
        // Every pair up to `max_pairs` has been handed out.
        return Ok(Acquired::NoWork);
    };
    let task_id = insert_on_demand_task(conn, job.id, Some(seed)).await?;
    super::insert_game_request(
        conn,
        task_id,
        &request,
        config.player1_config_id,
        config.player2_config_id,
    )
    .await?;
    Ok(Acquired::Task { task_id, request: TaskRequest::GamePairs(request), created: true })
}

async fn generate_leave_gen(
    conn: &mut PgConnection,
    job: &Job,
    identity: &WorkerIdentity,
) -> AppResult<Acquired> {
    let config =
        sqlx::query_as::<_, LeaveConfig>("SELECT * FROM job_leave_config WHERE job_id = $1")
            .bind(job.id)
            .fetch_one(&mut *conn)
            .await?;

    // `acquire` holds the job's dispatch lock for the rest of this transaction,
    // taken before anything here is read: what to hand out, and whether the
    // generation can be closed, are decisions that must not be made from a
    // view of the job that another claim is in the middle of changing. See
    // PLAN.md's leave-generation claim steps.

    // A reopened task -- its claim timed out -- is reissued before a new one is
    // generated, as for every job type, but only here: after the lock, so the
    // reissued claim is visible to the in-flight check of every claim that
    // follows it, and only for the current generation. A task from a
    // generation that has since closed is left alone; its racks would be
    // played with a KLV that is no longer current, and its result discarded.
    let Some(generation) = leave_gen::current_generation(&mut *conn, job.id, &config).await? else {
        return Ok(Acquired::JobFinished);
    };

    // While this generation's transition is running there is nothing to hand
    // out for it, and that has to be checked before the reissue below rather
    // than only in `next_step`. The generation does not read as closed until
    // the transition commits its artifact row, so without this a task left
    // `available` by a lapsed claim would be reissued mid-transition: the
    // worker would play it and fold its occurrences into the very rows the
    // transition is streaming, so the KLV it uploaded would no longer be
    // reproducible from the database -- and a hash mismatch is the one signal
    // `rebuild_artifacts` reserves for a corrupted object.
    if leave_gen::transition_in_progress(&mut *conn, job.id, generation).await? {
        return Ok(Acquired::NoWork);
    }

    // Generations past the first get their rack universe when a claim first
    // asks for work in one, rather than from the transition that closed the
    // generation before -- but not inside the claim: it is millions of rows,
    // and a request the client gives up on rolls it back. The caller seeds it
    // on its own task. Checked before anything reads `leave_rack_progress`,
    // which is what selection and the in-flight check are about to do.
    if !leave_gen::universe_exists(&mut *conn, job.id, generation).await? {
        return Ok(Acquired::NeedsUniverse { generation });
    }
    let job_data = load_job_data(&mut *conn, job.id).await?;

    if let Some(task_id) = next_available(&mut *conn, job.id, identity, Some(generation)).await? {
        let request = load_request(conn, job.job_type, task_id).await?;
        return Ok(Acquired::Task { task_id, request, created: false });
    }

    match leave_gen::next_step(conn, job.id, &config, &job_data).await? {
        leave_gen::LeaveGenStep::Dispatch(request) => {
            let task_id = insert_on_demand_task(conn, job.id, None).await?;
            leave_gen::insert_request(conn, task_id, &request).await?;
            Ok(Acquired::Task { task_id, request: TaskRequest::LeaveGeneration(request), created: true })
        }
        leave_gen::LeaveGenStep::Transition { generation } => {
            Ok(Acquired::NeedsGenerationTransition { generation })
        }
        leave_gen::LeaveGenStep::Finished => Ok(Acquired::JobFinished),
        // Another worker's request is aggregating the generation. This one has
        // nothing to do until that finishes, and the next job in the
        // scheduler's order may well have work.
        leave_gen::LeaveGenStep::TransitionInProgress { .. } => Ok(Acquired::NoWork),
        leave_gen::LeaveGenStep::NoWorkYet => Ok(Acquired::NoWork),
    }
}

/// On-demand tasks are inserted `available` and immediately claimed by the
/// caller in the same transaction, so the counter bookkeeping is identical on
/// every path.
async fn insert_on_demand_task(
    conn: &mut PgConnection,
    job_id: Uuid,
    seed: Option<i64>,
) -> AppResult<Uuid> {
    Ok(sqlx::query_scalar::<_, Uuid>(
        "INSERT INTO tasks (job_id, seed, state) VALUES ($1, $2, 'available') RETURNING id",
    )
    .bind(job_id)
    .bind(seed)
    .fetch_one(conn)
    .await?)
}

/// Checks a batch against the size the task was dispatched with.
///
/// Lives here rather than in `process_response` because it needs the request,
/// which the pure validation step does not have. It is the one submission-time
/// check that can catch a worker reporting work it did not do: the batch size
/// was fixed when the task was handed out, so a result of any other size is
/// answering a question nobody asked.
async fn check_batch_size(
    conn: &mut PgConnection,
    job: &Job,
    task_id: Uuid,
    reported_games: i32,
) -> AppResult<()> {
    super::plausibility::check_against_task(
        conn,
        job,
        task_id,
        &super::plausibility::Reported { games: Some(reported_games) },
    )
    .await
}

/// Validate, normalize and store a worker submission.
///
/// `first_result` says whether this is the first accepted result for its task,
/// which the caller reads from the task's `accepted_count` under the task's row
/// lock. Only a first result adds to the job's running totals or folds into a
/// leave generation: redundant claims replay the same deterministic work.
pub async fn store_result(
    conn: &mut PgConnection,
    job: &Job,
    task_id: Uuid,
    claim_id: Uuid,
    first_result: bool,
    payload: serde_json::Value,
) -> AppResult<()> {
    fn decode<T: serde::de::DeserializeOwned>(payload: serde_json::Value) -> AppResult<T> {
        serde_json::from_value(payload)
            .map_err(|e| AppError::bad_request(format!("malformed task response: {e}")))
    }

    match job.job_type {
        JobType::OpeningRack => {
            let record = opening_rack::OpeningRackHandler::process_response(decode(payload)?)?;
            let racks: Vec<String> =
                record.positions.iter().map(|p| p.rack.clone()).collect();
            opening_rack::check_batch_against_task(conn, task_id, &racks).await?;
            opening_rack::OpeningRackHandler::insert_record(conn, job.id, task_id, claim_id, &record)
                .await?;
            // One row per rack, and the unique index on (task_claim_id, rack)
            // means the insert above would have failed on a duplicate, so the
            // submission's length is its distinct-rack count. Racks never
            // repeat across tasks either: each task analyses its own slice of
            // the enumerated space.
            count_first_result(
                conn,
                job,
                first_result,
                "racks_analyzed",
                record.positions.len() as i64,
            )
            .await
        }
        JobType::Games => {
            let record = game::GameHandler::process_response(decode(payload)?)?;
            check_batch_size(conn, job, task_id, record.all_games.games).await?;
            game::GameHandler::insert_record(conn, job.id, task_id, claim_id, &record).await?;
            count_first_result(conn, job, first_result, "games_completed", record.all_games.games as i64)
                .await
        }
        JobType::GamePairs => {
            let record = game_pair::GamePairHandler::process_response(decode(payload)?)?;
            check_batch_size(conn, job, task_id, record.all_games.games).await?;
            game_pair::GamePairHandler::insert_record(conn, job.id, task_id, claim_id, &record).await?;
            // Games, not pairs, for both job types: the pairs count is half of
            // it and is derived where it is displayed.
            count_first_result(conn, job, first_result, "games_completed", record.all_games.games as i64)
                .await
        }
        JobType::LeaveGeneration => {
            let record = leave_gen::LeaveGenHandler::process_response(decode(payload)?)?;
            if first_result {
                leave_gen::LeaveGenHandler::insert_record(conn, job.id, task_id, claim_id, &record)
                    .await
            } else {
                leave_gen::credit_claim(conn, task_id, claim_id, &record).await
            }
        }
    }
}

/// Add this submission's work to one of the job's running progress totals, but
/// only if it is the first accepted result for its task.
///
/// The reads these totals replace both selected one result per task -- the
/// aggregates they summed describe the same deterministic work on every
/// redundant claim, so counting all of them would multiply the total by the
/// job's redundancy (PLAN.md, "What these reads cost"). "First" comes from the
/// task's `accepted_count`, read by `submit_result` under the task's row lock
/// before anything is stored: every accepted result increments it in the
/// transaction that stores the result, and that transaction holds the same
/// lock, so two submissions arriving together cannot both read zero. It used to
/// be decided by counting the rows just written, which for an opening-rack
/// batch was a read of up to 10,000 of them to learn one bit. Update and store
/// share the submission's transaction, so a submission that later fails
/// contributes neither.
///
/// The update takes a row lock on `jobs`, so two submissions for the same job
/// serialize here for as long as the lock is held. A task is minutes of work, so
/// that is a lock every few seconds at most on a busy job, and the alternative
/// -- the count these totals exist to avoid -- was seconds of CPU per page view.
async fn count_first_result(
    conn: &mut PgConnection,
    job: &Job,
    first_result: bool,
    column: &str,
    amount: i64,
) -> AppResult<()> {
    if !first_result {
        return Ok(());
    }

    // `column` is one of two literals chosen in this file, never worker input.
    sqlx::query(&format!("UPDATE jobs SET {column} = {column} + $2 WHERE id = $1"))
        .bind(job.id)
        .bind(amount)
        .execute(&mut *conn)
        .await?;
    Ok(())
}

/// The part of job initialization that cannot run inside the creating
/// transaction: generation 1's zeroed KLV is a multi-megabyte build and an
/// object-store write. Called after the transaction commits, and again at
/// activation if it has not happened yet. Idempotent.
pub async fn initialize_job_artifacts(
    pool: &sqlx::PgPool,
    artifacts: &ArtifactStore,
    job: &Job,
) -> AppResult<()> {
    if job.job_type != JobType::LeaveGeneration {
        return Ok(());
    }
    let mut conn = pool.acquire().await?;
    let job_data = load_job_data(&mut conn, job.id).await?;
    drop(conn);
    leave_gen::seed_zero_generation(pool, artifacts, job.id, &job_data.letterdist).await?;
    Ok(())
}

/// Whether a job has everything `initialize_job_artifacts` writes. Only leave
/// generation writes anything.
pub async fn job_artifacts_ready(pool: &sqlx::PgPool, job: &Job) -> AppResult<bool> {
    if job.job_type != JobType::LeaveGeneration {
        return Ok(true);
    }
    Ok(sqlx::query_scalar::<_, bool>(
        "SELECT EXISTS (SELECT 1 FROM leave_generation_artifacts
                        WHERE job_id = $1 AND generation = 0)",
    )
    .bind(job.id)
    .fetch_one(pool)
    .await?)
}
